version: "3"

services:

  mongodb:
    container_name: ${DB_CONTAINER_NAME}
    image: "mongo:4.2.16-bionic"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      retries: 5

  swift_app:
    container_name: ${SWIFT_APP}
    image: ${SWIFT_APP}
    build:
      dockerfile: Dockerfile
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"
      